name: CI – Build & Push Docker

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    name: Build & Push to ECR
    runs-on: ubuntu-latest

    # Definimos as credenciais e região AWS para todos os passos deste job:
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: ./mvnw clean package -DskipTests

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: |
            675080425843.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and Push Docker image
        env:
          ECR_REPOSITORY: 675080425843.dkr.ecr.us-east-1.amazonaws.com/backend-challenge
        run: |
          docker build \
            -f src/main/docker/Dockerfile.jvm \
            -t $ECR_REPOSITORY:latest .
          docker push $ECR_REPOSITORY:latest
