name: CI – Build & Push Docker

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    name: Build & Push to ECR
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: ./mvnw clean package -DskipTests

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry: 675080425843.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and Push Docker image
        env:
          ECR_REPOSITORY: 675080425843.dkr.ecr.us-east-1.amazonaws.com/backend-challenge
        run: |
          docker build \
            -f src/main/docker/Dockerfile.jvm \
            -t $ECR_REPOSITORY:latest .
          docker push $ECR_REPOSITORY:latest
